name: PHP Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lint:
    name: Lint and Code Style
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        os: ['ubuntu-24.04']

    steps:
      - name: Checkout code base
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpcs

      - name: Setup dependencies
        run: composer require -n --no-progress overtrue/phplint

      - name: PHP Lint
        if: success() || matrix.allow_failure
        run: ./vendor/bin/phplint -n --exclude={^vendor/.*} -- .

      - name: PHP CodeSniffer
        if: success() || matrix.allow_failure
        run: phpcs -wps --colors
